version: '3'
networks:
  proxy:
    external: true
  internal:
    external: false
  mongodb_network:
    external: true

services:
  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" # Assuming Traefik runs on the "proxy" network
      - "traefik.http.routers.ideabox.rule=Host(`yourdomain.com`)" # Replace with your domain
      - "traefik.http.routers.ideabox.entrypoints=websecure"
      - "traefik.http.routers.ideabox.tls.certresolver=defaultresolver"
    networks:
      - proxy
      - internal
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://username:password@mongo:27017/db_name  # Replace with actual credentials and MongoDB service name
    stop_signal: SIGINT
    networks:
      - internal
      - mongodb_network  # Adding the MongoDB external network here
    restart: unless-stopped