version: '3'
networks:
  proxy:
    external: true
  internal:
    external: false

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" # Assuming Traefik runs on the "proxy" network
      - "traefik.http.routers.ideabox.rule=Host(`yourdomain.com`)" # Replace with your domain
      - "traefik.http.routers.ideabox.entrypoints=websecure"
      - "traefik.http.routers.ideabox.tls.certresolver=defaultresolver"
    networks:
      - proxy
      - internal

  backend:
    build: ./backend
    stop_signal: SIGINT
    networks:
      - internal
